name: CI/CD Pipeline Prueba

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

     
    - name: Verify AWS credentials file
      run: cat ~/.aws/credentials || echo "AWS credentials file not found"


    - name: Manually set up AWS credentials
      run: |
        mkdir -p ~/.aws
        echo "[default]" > ~/.aws/credentials
        echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
        echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
        echo "[default]" > ~/.aws/config
        echo "region=us-east-1" >> ~/.aws/config
    
   
    - name: Debug AWS CLI
      run: |
        aws sts get-caller-identity --profile default
       
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.9

    - name: Terraform init
      run: terraform init

    - name: Terraform plan
      run: terraform plan

    

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install awscli boto3

    - name: Check if lambda.zip exists
      run: ls -l ./lambda.zip


    - name: Upload to S3
      run: |
        aws s3 cp ./lambda.zip s3://lambda-bucket23/lambda.zip

    - name: Deploy Lambda and API Gateway
      run: |
        aws lambda update-function-code --function-name your-lambda-function-name --s3-bucket lambda-bucket23 --s3-key lambda.zip
        aws apigateway create-deployment --rest-api-id l8lxt8gntl --stage-name prod

    - name: Test API Gateway
      run: |
        curl -X GET https://l8lxt8gntl.execute-api.us-east-1.amazonaws.com/proda