name: CI/CD Pipeline Prueba

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2


    - name: Manually set up AWS credentials
      run: |
        mkdir -p ~/.aws
        echo "[default]" > ~/.aws/credentials
        echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
        echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
        echo "[default]" > ~/.aws/config
        echo "region=us-east-1" >> ~/.aws/config
    
  
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.9

    - name: Terraform init
      run: terraform init

    - name: Terraform plan
      run: terraform plan

    #- name: Terraform Apply
    #  run: terraform apply -auto-approve
    

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install awscli boto3

    - name: Check if lambda.zip exists
      run: ls -l ./lambda.zip

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    

    - name: Debug AWS CLI Credentials
      run: aws sts get-caller-identity


    - name: Upload to S3
      run: |
        aws s3 cp ./lambda.zip s3://lambda-bucket23/lambda.zip

    - name: Deploy Lambda and API Gateway
      run: |
        aws lambda update-function-code --function-name mi-funcion-lambda --s3-bucket lambda-bucket23 --s3-key lambda.zip
        aws apigateway create-deployment --rest-api-id l8lxt8gntl --stage-name prod

    - name: Test API Gateway
      run: |
        curl -X GET https://l8lxt8gntl.execute-api.us-east-1.amazonaws.com/prod/lambda