name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Zip Lambda
        run: |
          zip -r lambda.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: lambda-zip
          path: lambda.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: lambda-zip

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Deploy Lambda function
        run: |
          aws lambda update-function-code --function-name <mi-funcion-lambda> --zip-file fileb://lambda.zip

      - name: Deploy API Gateway
        run: |
          aws apigateway create-deployment --rest-api-id <l8lxt8gntl> --stage-name prod
