name: CI/CD Pipeline for AWS Lambda, API Gateway, and Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Etapa de Construcci贸n (Build)
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout del c贸digo
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Configurar AWS CLI con AWS Credentials
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 3: Instalar Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.2.5'

      # Step 4: Inicializar Terraform
      - name: Terraform Init
        run: terraform init

      # Step 5: Validar Terraform
      - name: Terraform Validate
        run: terraform validate

      # Step 6: Crear un Plan de Terraform
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Step 7: Aplicar el Plan de Terraform (Inicia la infraestructura de AWS)
      #- name: Terraform Apply
      #  run: terraform apply -auto-approve tfplan

  # Etapa de Despliegue (Deploy)
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Step 1: Checkout del c贸digo
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Configurar AWS CLI (para el despliegue)
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 3: Subir C贸digo Lambda a S3 (si se necesita)
      - name: Upload Lambda code to S3
        run: aws s3 cp ./lambda.zip s3://lambda-bucket23/lambda.zip

      # Step 4: Actualizar Lambda
      - name: Update Lambda Function
        run: |
          aws lambda update-function-code \
            --function-name mi-funcion-lambda \
            --s3-bucket lambda-bucket23 \
            --s3-key lambda.zip

      # Step 5: Actualizar API Gateway (si se requiere)
      - name: Deploy API Gateway
        run: |
          aws apigateway create-deployment \
            --rest-api-id l8lxt8gntl \
            --stage-name prod

      # Step 6: Probar API (opcional)
      - name: Test API
        run: |
          curl -X GET https://l8lxt8gntl.execute-api.us-east-1.amazonaws.com/prod/lambda

